export const data = {
  reportDetailParts: {
    reportDetailPart1: {
      reportTitle: "كارنامه مديران استاني",
      f1PicText: "عكس خبرنگار",
      f1PicValue: "2424.jpg",
      f2PicText: "عملكرد",
      f2PicValue: "redimage.jpg",
    },
    reportDetailPart2: [
      {
        fieldIndex: 1,
        fieldText: "",
        fieldType: "text+",
        fieldValue: "احسان احساني",
      },
      {
        fieldIndex: 2,
        fieldText: "رتبه خبرنگار",
        fieldType: "star",
        fieldValue: "4",
      },
      {
        fieldIndex: 3,
        fieldText: "حوزه خبرنگار\r\n",
        fieldType: "text",
        fieldValue: "استان قم",
      },
      {
        fieldIndex: 4,
        fieldText: "كد پرسنلي",
        fieldType: "text",
        fieldValue: "53319",
      },
      {
        fieldIndex: 5,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 6,
        fieldText: "دوره ارزيابي\r\n",
        fieldType: "text",
        fieldValue: "فروردین ماه سال 1402",
      },
      {
        fieldIndex: 7,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 8,
        fieldText: "وضعيت عملكرد\r\n",
        fieldType: "text",
        fieldValue: "تذکر کتبی",
      },
      {
        fieldIndex: 10,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
    ],
    reportDetailPart3: [
      {
        fieldIndex: 1,
        fieldText: "امتياز كل استان",
        fieldType: "type1",
        fieldValue: "132",
      },
      {
        fieldIndex: 2,
        fieldText: "رتبه استان در خبرگزاري",
        fieldType: "type2",
        fieldValue: "14",
      },
      {
        fieldIndex: 3,
        fieldText: "ميزان بازديد استان",
        fieldType: "type2",
        fieldValue: "1239000",
      },
      {
        fieldIndex: 4,
        fieldText: "اغلاط املايي و انشايي در استان",
        fieldType: "type2",
        fieldValue: "15",
      },
      {
        fieldIndex: 5,
        fieldText: "تراز كل استان",
        fieldType: "type4",
        fieldValue: "254",
      },
      {
        fieldIndex: 6,
        fieldText: "بدهكار",
        fieldType: "type1",
        fieldValue: "",
      },
      {
        fieldIndex: 7,
        fieldText: "بستانكار",
        fieldType: "type1",
        fieldValue: "",
      },
      {
        fieldIndex: 8,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 9,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 10,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 11,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 12,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 13,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 14,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 15,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 16,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 17,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 18,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 19,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 20,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 21,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 22,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 23,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 24,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 25,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 26,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 27,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 28,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 29,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 30,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
      {
        fieldIndex: 31,
        fieldText: "",
        fieldType: "",
        fieldValue: "",
      },
    ],
    reportDetailPart4: [
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 1,
        fieldText: "خبر توليدي\r\n",
        fieldValue: "120",
        fieldPercent: "30",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 2,
        fieldText: "خبر دريافتي",
        fieldValue: "100",
        fieldPercent: "25",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 3,
        fieldText: "خبر اختصاصی (گفتگو)\r\n",
        fieldValue: "80",
        fieldPercent: "20",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 4,
        fieldText: "مصاحبه\r\n",
        fieldValue: "40",
        fieldPercent: "10",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 5,
        fieldText: "گزارش تحلیلی\r\n",
        fieldValue: "20",
        fieldPercent: "5",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 6,
        fieldText: "خبر پوششي",
        fieldValue: "20",
        fieldPercent: "5",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 7,
        fieldText: "ساير فرمتها",
        fieldValue: "20",
        fieldPercent: "5",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 8,
        fieldText: "",
        fieldValue: "",
        fieldPercent: "",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 9,
        fieldText: "",
        fieldValue: "",
        fieldPercent: "",
      },
      {
        newsFormatType: "قالبهاي خبري",
        fieldIndex: 10,
        fieldText: "",
        fieldValue: "",
        fieldPercent: "",
      },
    ],
    reportDetailPart5: {
      crType: "1",
      cR_Range1: "30",
      cR_Range2: "60",
      cR_Range3: "90",
      cR_Range4: "120",
      cR_Range5: "200",
      cR_Range6: "250",
      cR_Range7: "350",
      cR_Range8: "400",
      cR_Range9: "450",
      cR_Range10: "500",
      cR_Title1: "نرخ كليك استان",
      cR_Value1: "",
      cR_Title2: "",
      cR_Value2: "",
    },
    reportDetailPart6: {
      lnType: "1",
      lN_Range01: "5",
      lN_Range02: "15",
      lN_Range03: "30",
      lN_Range04: "40",
      lN_Range05: "50",
      lN_Range06: "60",
      lN_Range07: "70",
      lN_Range08: "80",
      lN_Range09: "90",
      lN_Range10: "100",
      lN_Title1: "سرعت(تاخير)",
      lN_Value1: "",
    },
    iN_Title: "جامعيت خبر\r\n",
    iN_Value: "",
    eC_Title: "تطابق ارزيابي",
    eC_Value: "",
    rN_Title: "تعداد بازنشر\r\n",
    rN_Value: "",
  },
};
